#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

#define XPAR_XGPIO_NUM_INSTANCES 8

/* Definitions for peripheral AXI_GPIO_BUTTONS */
#define XPAR_AXI_GPIO_BUTTONS_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXI_GPIO_BUTTONS_BASEADDR 0x40000000
#define XPAR_AXI_GPIO_BUTTONS_HIGHADDR 0x40000fff
#define XPAR_AXI_GPIO_BUTTONS_INTERRUPT_PRESENT 0x0
#define XPAR_AXI_GPIO_BUTTONS_IS_DUAL 0x0
#define XPAR_AXI_GPIO_BUTTONS_GPIO_WIDTH 0x4

/* Canonical definitions for peripheral AXI_GPIO_BUTTONS */
#define XPAR_XGPIO_0_BASEADDR 0x40000000
#define XPAR_XGPIO_0_HIGHADDR 0x40000fff
#define XPAR_XGPIO_0_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_0_GPIO_WIDTH 0x4
#define XPAR_XGPIO_0_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_0_IS_DUAL 0x0

/* Definitions for peripheral AXI_GPIO_JA */
#define XPAR_AXI_GPIO_JA_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXI_GPIO_JA_BASEADDR 0x40001000
#define XPAR_AXI_GPIO_JA_HIGHADDR 0x40001fff
#define XPAR_AXI_GPIO_JA_INTERRUPT_PRESENT 0x0
#define XPAR_AXI_GPIO_JA_IS_DUAL 0x0
#define XPAR_AXI_GPIO_JA_GPIO_WIDTH 0x8

/* Canonical definitions for peripheral AXI_GPIO_JA */
#define XPAR_XGPIO_1_BASEADDR 0x40001000
#define XPAR_XGPIO_1_HIGHADDR 0x40001fff
#define XPAR_XGPIO_1_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_1_GPIO_WIDTH 0x8
#define XPAR_XGPIO_1_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_1_IS_DUAL 0x0

/* Definitions for peripheral AXI_GPIO_JB */
#define XPAR_AXI_GPIO_JB_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXI_GPIO_JB_BASEADDR 0x40002000
#define XPAR_AXI_GPIO_JB_HIGHADDR 0x40002fff
#define XPAR_AXI_GPIO_JB_INTERRUPT_PRESENT 0x0
#define XPAR_AXI_GPIO_JB_IS_DUAL 0x0
#define XPAR_AXI_GPIO_JB_GPIO_WIDTH 0x8

/* Canonical definitions for peripheral AXI_GPIO_JB */
#define XPAR_XGPIO_2_BASEADDR 0x40002000
#define XPAR_XGPIO_2_HIGHADDR 0x40002fff
#define XPAR_XGPIO_2_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_2_GPIO_WIDTH 0x8
#define XPAR_XGPIO_2_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_2_IS_DUAL 0x0

/* Definitions for peripheral AXI_GPIO_JC */
#define XPAR_AXI_GPIO_JC_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXI_GPIO_JC_BASEADDR 0x40003000
#define XPAR_AXI_GPIO_JC_HIGHADDR 0x40003fff
#define XPAR_AXI_GPIO_JC_INTERRUPT_PRESENT 0x0
#define XPAR_AXI_GPIO_JC_IS_DUAL 0x0
#define XPAR_AXI_GPIO_JC_GPIO_WIDTH 0x8

/* Canonical definitions for peripheral AXI_GPIO_JC */
#define XPAR_XGPIO_3_BASEADDR 0x40003000
#define XPAR_XGPIO_3_HIGHADDR 0x40003fff
#define XPAR_XGPIO_3_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_3_GPIO_WIDTH 0x8
#define XPAR_XGPIO_3_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_3_IS_DUAL 0x0

/* Definitions for peripheral AXI_GPIO_JXADC */
#define XPAR_AXI_GPIO_JXADC_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXI_GPIO_JXADC_BASEADDR 0x40004000
#define XPAR_AXI_GPIO_JXADC_HIGHADDR 0x40004fff
#define XPAR_AXI_GPIO_JXADC_INTERRUPT_PRESENT 0x0
#define XPAR_AXI_GPIO_JXADC_IS_DUAL 0x0
#define XPAR_AXI_GPIO_JXADC_GPIO_WIDTH 0x8

/* Canonical definitions for peripheral AXI_GPIO_JXADC */
#define XPAR_XGPIO_4_BASEADDR 0x40004000
#define XPAR_XGPIO_4_HIGHADDR 0x40004fff
#define XPAR_XGPIO_4_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_4_GPIO_WIDTH 0x8
#define XPAR_XGPIO_4_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_4_IS_DUAL 0x0

/* Definitions for peripheral AXI_GPIO_LEDS */
#define XPAR_AXI_GPIO_LEDS_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXI_GPIO_LEDS_BASEADDR 0x40005000
#define XPAR_AXI_GPIO_LEDS_HIGHADDR 0x40005fff
#define XPAR_AXI_GPIO_LEDS_INTERRUPT_PRESENT 0x0
#define XPAR_AXI_GPIO_LEDS_IS_DUAL 0x0
#define XPAR_AXI_GPIO_LEDS_GPIO_WIDTH 0x10

/* Canonical definitions for peripheral AXI_GPIO_LEDS */
#define XPAR_XGPIO_5_BASEADDR 0x40005000
#define XPAR_XGPIO_5_HIGHADDR 0x40005fff
#define XPAR_XGPIO_5_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_5_GPIO_WIDTH 0x10
#define XPAR_XGPIO_5_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_5_IS_DUAL 0x0

/* Definitions for peripheral AXI_GPIO_SEVEN_SEG */
#define XPAR_AXI_GPIO_SEVEN_SEG_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXI_GPIO_SEVEN_SEG_BASEADDR 0x40006000
#define XPAR_AXI_GPIO_SEVEN_SEG_HIGHADDR 0x40006fff
#define XPAR_AXI_GPIO_SEVEN_SEG_INTERRUPT_PRESENT 0x0
#define XPAR_AXI_GPIO_SEVEN_SEG_IS_DUAL 0x1
#define XPAR_AXI_GPIO_SEVEN_SEG_GPIO_WIDTH 0x4

/* Canonical definitions for peripheral AXI_GPIO_SEVEN_SEG */
#define XPAR_XGPIO_6_BASEADDR 0x40006000
#define XPAR_XGPIO_6_HIGHADDR 0x40006fff
#define XPAR_XGPIO_6_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_6_GPIO_WIDTH 0x4
#define XPAR_XGPIO_6_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_6_IS_DUAL 0x1

/* Definitions for peripheral AXI_GPIO_SWITCHES */
#define XPAR_AXI_GPIO_SWITCHES_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXI_GPIO_SWITCHES_BASEADDR 0x40007000
#define XPAR_AXI_GPIO_SWITCHES_HIGHADDR 0x40007fff
#define XPAR_AXI_GPIO_SWITCHES_INTERRUPT_PRESENT 0x0
#define XPAR_AXI_GPIO_SWITCHES_IS_DUAL 0x0
#define XPAR_AXI_GPIO_SWITCHES_GPIO_WIDTH 0x10

/* Canonical definitions for peripheral AXI_GPIO_SWITCHES */
#define XPAR_XGPIO_7_BASEADDR 0x40007000
#define XPAR_XGPIO_7_HIGHADDR 0x40007fff
#define XPAR_XGPIO_7_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_7_GPIO_WIDTH 0x10
#define XPAR_XGPIO_7_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_7_IS_DUAL 0x0

#define XPAR_XTMRCTR_NUM_INSTANCES 4

/* Definitions for peripheral AXI_TIMER_0 */
#define XPAR_AXI_TIMER_0_COMPATIBLE "xlnx,axi-timer-2.0"
#define XPAR_AXI_TIMER_0_BASEADDR 0x40009000
#define XPAR_AXI_TIMER_0_HIGHADDR 0x40009fff
#define XPAR_AXI_TIMER_0_CLOCK_FREQUENCY 0x5f5e100

/* Canonical definitions for peripheral AXI_TIMER_0 */
#define XPAR_XTMRCTR_0_BASEADDR 0x40009000
#define XPAR_XTMRCTR_0_HIGHADDR 0x40009fff
#define XPAR_XTMRCTR_0_COMPATIBLE "xlnx,axi-timer-2.0"
#define XPAR_XTMRCTR_0_CLOCK_FREQUENCY 0x5f5e100

/* Definitions for peripheral AXI_TIMER_1 */
#define XPAR_AXI_TIMER_1_COMPATIBLE "xlnx,axi-timer-2.0"
#define XPAR_AXI_TIMER_1_BASEADDR 0x4000a000
#define XPAR_AXI_TIMER_1_HIGHADDR 0x4000afff
#define XPAR_AXI_TIMER_1_CLOCK_FREQUENCY 0x5f5e100

/* Canonical definitions for peripheral AXI_TIMER_1 */
#define XPAR_XTMRCTR_1_BASEADDR 0x4000a000
#define XPAR_XTMRCTR_1_HIGHADDR 0x4000afff
#define XPAR_XTMRCTR_1_COMPATIBLE "xlnx,axi-timer-2.0"
#define XPAR_XTMRCTR_1_CLOCK_FREQUENCY 0x5f5e100

/* Definitions for peripheral AXI_TIMER_2 */
#define XPAR_AXI_TIMER_2_COMPATIBLE "xlnx,axi-timer-2.0"
#define XPAR_AXI_TIMER_2_BASEADDR 0x4000b000
#define XPAR_AXI_TIMER_2_HIGHADDR 0x4000bfff
#define XPAR_AXI_TIMER_2_CLOCK_FREQUENCY 0x5f5e100

/* Canonical definitions for peripheral AXI_TIMER_2 */
#define XPAR_XTMRCTR_2_BASEADDR 0x4000b000
#define XPAR_XTMRCTR_2_HIGHADDR 0x4000bfff
#define XPAR_XTMRCTR_2_COMPATIBLE "xlnx,axi-timer-2.0"
#define XPAR_XTMRCTR_2_CLOCK_FREQUENCY 0x5f5e100

/* Definitions for peripheral AXI_TIMER_3 */
#define XPAR_AXI_TIMER_3_COMPATIBLE "xlnx,axi-timer-2.0"
#define XPAR_AXI_TIMER_3_BASEADDR 0x4000c000
#define XPAR_AXI_TIMER_3_HIGHADDR 0x4000cfff
#define XPAR_AXI_TIMER_3_CLOCK_FREQUENCY 0x5f5e100

/* Canonical definitions for peripheral AXI_TIMER_3 */
#define XPAR_XTMRCTR_3_BASEADDR 0x4000c000
#define XPAR_XTMRCTR_3_HIGHADDR 0x4000cfff
#define XPAR_XTMRCTR_3_COMPATIBLE "xlnx,axi-timer-2.0"
#define XPAR_XTMRCTR_3_CLOCK_FREQUENCY 0x5f5e100

#define XPAR_XUARTLITE_NUM_INSTANCES 1

/* Definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_AXI_UARTLITE_0_COMPATIBLE "xlnx,axi-uartlite-2.0"
#define XPAR_AXI_UARTLITE_0_BASEADDR 0x40008000
#define XPAR_AXI_UARTLITE_0_HIGHADDR 0x40008fff
#define XPAR_AXI_UARTLITE_0_BAUDRATE 0x2580
#define XPAR_AXI_UARTLITE_0_USE_PARITY 0x0
#define XPAR_AXI_UARTLITE_0_ODD_PARITY 0x0
#define XPAR_AXI_UARTLITE_0_DATA_BITS 0x8

/* Canonical definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_XUARTLITE_0_BASEADDR 0x40008000
#define XPAR_XUARTLITE_0_HIGHADDR 0x40008fff
#define XPAR_XUARTLITE_0_BAUDRATE 0x2580
#define XPAR_XUARTLITE_0_COMPATIBLE "xlnx,axi-uartlite-2.0"
#define XPAR_XUARTLITE_0_DATA_BITS 0x8
#define XPAR_XUARTLITE_0_ODD_PARITY 0x0
#define XPAR_XUARTLITE_0_USE_PARITY 0x0

#define XPAR_LMB_BRAM_0_BASEADDRESS 0x0
#define XPAR_LMB_BRAM_0_HIGHADDRESS 0xffff
#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 100000000

#define XPAR_MICROBLAZE_ADDR_SIZE 32

#define XPAR_MICROBLAZE_USE_STACK_PROTECTION 0

/* Device ID */
#define XPAR_DEVICE_ID "7a35t"

#endif  /* end of protection macro */